### ISSUE TITLE
r.js optimizer, "backbone" module not available

### ISSUE THREAD

**Issue by chikamichi** [barc/backbone.giraffe#32]
Hi,

When using requirejs' optimizer, Giraffe fails at loading Backbone. Underscore is available on the window object, because Underscore does not uses `define`. My rjs conf thus has a shim for Underscore, Backbone, Backbone.Giraffe.

Everything is fine during development, but once rjs has run:

```
 Uncaught Error: Module name "backbone" has not been loaded yet for context: _. Use require([])
```

is raised [from the require call here](https://github.com/barc/backbone.giraffe/blob/master/src/backbone.giraffe.coffee#L15).

Somehow, it seems to be related to [the fact that a shimmed Backbone.Giraffe cannot rely on Backbone being loaded using AMD](http://requirejs.org/docs/api.html#config-shim) (see also [this](https://github.com/jrburke/r.js/issues/623)), so I tried this [neat "wrapShim" option](https://github.com/jrburke/r.js/blob/6391520ecb29eb51f4469859d06ed0bd2e09b625/build/example.build.js#L80), but with no success.

Is there any workaround to this?
Thx.

**Comment by ryanatkn** [comment]
@chikamichi Thanks for the info. Would you please verify this works before I do a new release?

**Comment by chikamichi** [comment]
Thank you, I will try asap.

**Comment by chikamichi** [comment]
@ryanatkn hi, sorry for the delay. I confirm that it works. You can release a new version :)

**Comment by ryanatkn** [comment]
Thanks!
