### ISSUE TITLE
0.2.7 breaks webpack support

### ISSUE THREAD

**Issue by cranberyxl** [barc/backbone.giraffe#33]
Updating to `0.2.7` prevents webpack from loading because the code drops into the `define.amd` block instead of the `module.exports` block. I'm investigating fixes, but for anyone using webpack, you'll have to drop back to `0.2.6`

**Comment by ryanatkn** [comment]
Thanks for the report. I'll look at it within the next week if you haven't found a solution.

Could it be as simple as swapping the order of the loader code?

changing:

    if define?.amd
      ...
    else if module?.exports
      ...

to:

    if module?.exports
      ...
    else if define?.amd
      ...

**Comment by ryanatkn** [comment]
I'm unable to reproduce this issue. Can you point out what I'm doing differently? I downloaded Giraffe and its deps with Bower, created `webpack.config.js` with the Bower loader, and created `entry.js` file with `require('backbone.giraffe')`. Running `webpack ./entry.js bundle.js` bundles everything up and the bundle seems to work in the browser.

**Comment by ryanatkn** [comment]
@cranberyxl Could you please provide some more info on how this is breaking with webpack?

**Comment by cranberyxl** [comment]
Include `backbone.giraffe.contrib` without including `backbone.giraffe` of that doesn't work, I can build an example

**Comment by ryanatkn** [comment]
@cranberyxl Thanks! I think v0.2.8 fixes this. It looks like webpack still falls into the AMD block, but it's using the same loader order as Backbone so I figured it's best to leave it as is.

**Comment by cranberyxl** [comment]
@ryanatkn `v0.2.8` works for me. Thanks for the fix
